package channel

import "strings"

// chatRunnerClaudeSettingsJSON 返回 chat runner 专用权限配置。
// 当前实现按要求与全局 runner 配置保持 1:1 完全一致（独立副本）。
func chatRunnerClaudeSettingsJSON() string {
	return strings.TrimSpace(chatRunnerClaudeSettingsJSONTemplate)
}

const chatRunnerClaudeSettingsJSONTemplate = `
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "sandbox": {
    "enabled": false
  },
  "permissions": {
    "defaultMode": "acceptEdits",
    "deny": [
      "Read(./.env)",
      "Read(./.env.*)",
      "Read(./secrets/**)",
      "Read(~/.ssh/**)",
      "Read(~/.aws/**)",
      "Edit(~/.ssh/**)",
      "Edit(~/.aws/**)",
      "Edit(~/.bashrc)",
      "Edit(~/.zshrc)",
      "Bash(git push*)",
      "Bash(rm *)"
    ],
    "ask": [
      "Bash(docker *)",
      "Bash(curl *)",
      "Bash(wget *)",
      "Bash(kill *)"
    ],
    "allow": [
      "Read(~/.claude/**)",
      "Edit(~/.claude/**)",
      "Read(/private/tmp/**)",
      "Edit(/private/tmp/**)",
      "Write(/private/tmp/**)",
      "Read(/tmp/**)",
      "Edit(/tmp/**)",
      "Write(/tmp/**)",
      "WebFetch(domain:github.com)",
      "WebFetch(domain:code.claude.com)",
      "Bash(dalek)",
      "Bash(dalek *)",
      "Bash(bash develop.sh)",
      "Bash(go build *)",
      "Bash(go test *)",
      "Bash(go run *)",
      "Bash(go mod *)",
      "Bash(go get *)",
      "Bash(go vet *)",
      "Bash(go fmt *)",
      "Bash(go generate *)",
      "Bash(go install *)",
      "Bash(go clean *)",
      "Bash(npm *)",
      "Bash(npx *)",
      "Bash(pnpm *)",
      "Bash(yarn *)",
      "Bash(bun *)",
      "Bash(node *)",
      "Bash(tsc *)",
      "Bash(pip install *)",
      "Bash(pip3 install *)",
      "Bash(pip list*)",
      "Bash(pip3 list*)",
      "Bash(pip show *)",
      "Bash(pip3 show *)",
      "Bash(pip freeze*)",
      "Bash(pip3 freeze*)",
      "Bash(uv *)",
      "Bash(python *)",
      "Bash(python3 *)",
      "Bash(cargo *)",
      "Bash(rustc *)",
      "Bash(make *)",
      "Bash(make)",
      "Bash(cmake *)",
      "Bash(mvn *)",
      "Bash(gradle *)",
      "Bash(composer *)",
      "Bash(gem *)",
      "Bash(bundle *)",
      "Bash(swift *)",
      "Bash(pod *)",
      "Bash(git add *)",
      "Bash(git commit *)",
      "Bash(git status*)",
      "Bash(git diff*)",
      "Bash(git log*)",
      "Bash(git branch*)",
      "Bash(git checkout*)",
      "Bash(git switch*)",
      "Bash(git merge*)",
      "Bash(git rebase*)",
      "Bash(git stash*)",
      "Bash(git fetch*)",
      "Bash(git pull*)",
      "Bash(git tag*)",
      "Bash(git show*)",
      "Bash(git rev-parse*)",
      "Bash(git cherry-pick*)",
      "Bash(echo *)",
      "Bash(echo)",
      "Bash(cp *)",
      "Bash(mv *)",
      "Bash(ls)",
      "Bash(ls *)",
      "Bash(cat *)",
      "Bash(date)",
      "Bash(date *)",
      "Bash(pwd)",
      "Bash(mkdir *)",
      "Bash(touch *)",
      "Bash(which *)",
      "Bash(env)",
      "Bash(env *)",
      "Bash(printenv)",
      "Bash(printenv *)",
      "Bash(head *)",
      "Bash(tail *)",
      "Bash(grep *)",
      "Bash(find *)",
      "Bash(wc *)",
      "Bash(sort *)",
      "Bash(uniq *)",
      "Bash(sed *)",
      "Bash(awk *)",
      "Bash(tr *)",
      "Bash(cut *)",
      "Bash(xargs *)",
      "Bash(test *)",
      "Bash([ *)",
      "Bash(true)",
      "Bash(false)",
      "Bash(sleep *)",
      "Bash(ps)",
      "Bash(ps *)"
    ]
  }
}
`
